### ISSUE TITLE
Missing topic: grant applications

### ISSUE THREAD

**Issue by konrad** [OpenScienceMOOC/Module-1-Open-Principles#1]
One part that is missing in the research cycle image above and is not covered in the MOOC is the opening of grant applications. It is important and helpful to learn if you could see what grant applications were successful and which were not. If anybody has a good article about this topic (I just have a[ link to this very outdated list](https://jabberwocky.weecology.org/2012/08/10/a-list-of-publicly-available-grant-proposals-in-the-biological-sciences/)) I would to suggest to add it to the link list in the Open Principle section just to raise awareness for this facet.

**Comment by Protohedgehog** [comment]
Hey @konrad! This module is well under development now. Reckon you can find a way to integrate this into the existing structure..? :)

**Comment by Protohedgehog** [comment]
Note to self: Make sure to include this too https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/Reading%20Material_Open%20Principles/Grigorov%20et%20al.%2C%202015.pdf

**Comment by Protohedgehog** [comment]
Hi @konrad, do you think there is still scope for this atm? Or do you think it might work better on the module for Open Access?

**Comment by Protohedgehog** [comment]
@konrad just wanted to ping again about this to check what you think about potentially shifting it to the module on OA! :)
