### ISSUE TITLE
New modes - more liberty or more pressures?

### ISSUE THREAD

**Issue by gorgikrlev** [OpenScienceMOOC/Module-1-Open-Principles#11]
@OpenScienceMOOC asked me to raise this here as a really cool discussion point. I went through the trouble of registering and posting this here, so this would better be an ace discussion ;):

Good point about researchers being more than their pubs. But are you not replicating the same logics by what you propose? Just with more things & more pressures for researchers? Autonomy & individuality are beneficial aspects, though.

**Comment by gorgikrlev** [comment]
Ha ha, sorry. Just edited the above. Of course I did not mean "ass discussion" but "ace discussion"...

**Comment by Protohedgehog** [comment]
This is a great question to ask, @gorgikrlev, thanks. So, what would be your suggested alternatives to using eg ORCID/OSF/ImpactStory/Publons. Are there ways to maintain autonomy and individuality without using such platforms to document your work?

I agree that some times it can all be too much, platform fatigue and all that, which is why we start with ORCID as this is a fully interoperably 'profile', so should reduce any pressure. In theory.

**Comment by gorgikrlev** [comment]
I think a one-stop-shop would help. Now you've got the above, plus google scholar, researchgate and Academia.org, Twitter, Linkedin, Xing etc. Then you'd want to spread the research on medium, The Conversation etc. It is super important to be present on all, but impossible to manage. ORCID is a good step but co-presence likely leading to more and more layers. Of course there are downsides to monopoly too, but also to striving to do all that, on top of research that is and all the other stuff academics are supposed to do...

I love the idea of being visible and autonomous, but these are aspects to keep in mind as we move on. 

Not the solution I know.

**Comment by Protohedgehog** [comment]
Well, actually, I guess what we are trying to do is pull people away from those platforms, and use more open, more effective ones! I guess one thing we could do in the future is document all possible alternatives, but the 101 innovations in scholarly communication already largely has this covered.

Science Communication will also play a factor later on in a different module.

**Comment by gorgikrlev** [comment]
Good ambition for sure! Yes, that would solve most of the problems. 

I just discovered I had seen the graph on Twitter but the project itself did not strike a note. Interesting in terms of branding. Yes, they seem to have it all. But what in fact would be useful is a life repository with categories, short profiles, maybe ratings and links to the tools. That did not seem to exist (or maybe I've only not looked thoroughly) but would be lots of effort of course.

**Comment by johav** [comment]
Yes, living repository is the way forward also in my view.
I have a Skype call tomorrow with Thomas Cruzier - the curator of http://connectedresearchers.com/online-tools-for-researchers/
on how to keep this alive - including user experience reviews and discipline specific reasonable workflows - also considering project specific demands - and suggested workflows with updates on https://101innovations.wordpress.com/workflows/

esp highlighting
- https://101innovations.files.wordpress.com/2018/02/workflows-wikimedia1.png
and 
- https://101innovations.files.wordpress.com/2018/02/workflows-open-science.png and of course
- https://osf.io/

**Comment by gorgikrlev** [comment]
Great johav, and thanks for pointing me to all these resources. Hope you'll find a good way to realise the ambition!

**Comment by Protohedgehog** [comment]
Just going to close this for now, can be re-opened if folks have more to discuss.
