### ISSUE TITLE
Create introductory video

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-1-Open-Principles#12]
Idea from #8 was to do an intro video for this module, with a series of participants simply describing what open science means to them.

Potential people to record:
Jo Havemann @johav  and Justin Ahinon @JustinyAhin 
Tobias Steiner 
Gareth O'Neill (suggestions to come from him too) @gtoneill 

Note from @tosteiner too was to include text-based versions for people who might not want to be on video. Suggest here to do a short Twitter campaign and screenshot various people's tweets for this.

**Comment by tosteiner** [comment]
@Protohedgehog Brilliant, thanks, Jon! 

Re: text-based option, this actually was - at least partly - motivated out of self-interest (I'd prefer not to appear on tape) 😉 Would be happy to share a tweet or quote, though 📓

**Comment by Protohedgehog** [comment]
Further idea for this - get one person from each continent for good geographical representation. Any thoughts on who would be good? @tosteiner @johav

**Comment by johav** [comment]
Sorry we didn't deliver from Ghana (Dec2018) - will have another attempt in April 2019 in Tanzania to get this done and will try n mobilize ppl remotely in the meantime.

Twitter poll sounds good for that - we can think of a strategy to get this done with regional distribution. 

New idea: Can we have an open Street map with those quotes of ppl and how they value open Science or just express their testimonial?

**Comment by evalantsoght** [comment]
Hi all! If you are planning to do the snippets from each continent, I can be chipping in from South America, if you need somebody from here.
I could also crowdsource some citations from my colleagues here.

**Comment by Protohedgehog** [comment]
@evalantsoght that would be awesome! We haven't quite finished the video idea just yet, but I would love you to be our SA 'representative' if possible.

@johav That might be a fun task. Is it possible, say, to crowdsource something like an annotated map, where people contribute their location and what open means to them/why they support open?

**Comment by BruceCaron** [comment]
Solid idea.  Let me know if you need any production help.

**Comment by Protohedgehog** [comment]
Just a quick note on this. So, if we want equal geographic representation, my suggestions on who to first approach/include are:
South America: @evalantsoght 
Africa: @JustinyAhin (AfricArxiv)
Asia: @dasaptaerwin (INARXIV)
Europe: Erzsébet Tóth-Czifra (DARIAH)
North America: Ashley Farley (Gates Foundation)
Australia/NZ: Cooper Smout (Free our knowledge)

Thoughts @BruceCaron @gtoneill @johav?

**Comment by etothczifra** [comment]
Challenge accepted from my side! :)

**Comment by Protohedgehog** [comment]
NEARLY DONE WITH THIS! Just waiting on me for now actually.
