### ISSUE TITLE
Open Science history bits and open culture

### ISSUE THREAD

**Issue by katjamatic** [OpenScienceMOOC/Module-1-Open-Principles#13]
Hi!

Here are some things that could be included for the first part - super short intro to the historical dimension of OS. (next a paragraph on open cultures)

---snip---
1) History

The commitment to opening Science to make it more transparent and accessible is nothing new. For some historians of science openness marks the beginning of science itself: with the printing press, the rise of publication markets and empirical methods in the early modern period came both the professionalization of scientists and the institutionalization of the Academies (David 2008). 

Today's Open Science movement dates about 30-40 years back to the 1970s and takes inspiration both from the history of "open source" [Kelty 2008] and the ideas developed for research collaboration in the context of "e-science" [Wouters and Beaulieu 2006]. At a first glance these approaches refer mainly to the technological dimension of opening up science by creating necessary tools and infrastructures. 

Opening up science often takes the form of a technological liberation and change of techniques in respective discourses. However, keeping in mind that science and technology "are politics by other means" [Latour 1987] - offering other means of power - it is vital to turn to the embedded politics of Open Science and its precursors.
---snip---

Bibliography:
David, Paul A., The Historical Origins of 'Open Science': An Essay on Patronage, Reputation and Common Agency Contracting in the Scientific Revolution (January 30, 2013). Capitalism and Society, Vol. 3, Issue 2, Article 5, 2008. Available at SSRN: https://ssrn.com/abstract=2209188
Kelty, C. M. (2008). Two bits: The cultural significance of free software. Duke University Press.
Latour, B. (1987). The pasteurization of French society, with irreductions.
Wouters, P., & Beaulieu, A. (2006). Imagining e-science beyond computation. In New infrastructures for knowledge production: Understanding e-science (pp. 48-70). IGI Global.

**Comment by Protohedgehog** [comment]
This is excellent, thanks so much, @katjamatic! I'll begin editing it in [here to the existing history section](https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/MAIN.md#cultures) to make sure that we have covered all of this.

**Comment by katjamatic** [comment]
Great, thanks. Will add stuff on Open Cultures soonish!
here is the image that i use normally.
![openculturesflower](https://user-images.githubusercontent.com/45576271/49859897-f2ade700-fdf8-11e8-820b-2ea11fb04495.png)

**Comment by Protohedgehog** [comment]
Fab, thank you @katjamatic! I love this image so much too. Can we re-use it and attribute you? Not sure what license this is under :)

**Comment by katjamatic** [comment]
sure, cc by

**Comment by Protohedgehog** [comment]
Awesome, thanks @katjamatic! Have now added the above content [here](https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/MAIN.md#cultures).  You can also directly edit that file if you find it easier too :)

**Comment by katjamatic** [comment]
Ah Cool. So i will add one more paragrpah on culture with the pic soon.
Thanks. Greetz from Madrid

Am Do., 13. Dez. 2018, 10:38 hat Jon Tennant <notifications@github.com>
geschrieben:

**Comment by johav** [comment]
Beautiful and important additions - thanks!
What about we convene strategic calls/meetings on what we aspects of the growing MOOC we can also package as articles (OA, Open Peer Reviewed) to raise awareness, push visibility and be more inclusive for those who don't use or follow up on Github?
Maybe the MOOC should have it's own OA journal :P

**Comment by Protohedgehog** [comment]
Nice idea! So one thing I already have done is created a Zenodo community for archiving all MOOC content here: https://zenodo.org/communities/open-science-mooc/

For each release of each module, we push it to Zenodo and it gets a versioned DOI and indexed for re-use. Each 'Main' document is also available as a PDF/HTML/Jupyter notebook format, and I can convert them to over things like epub too if needed.

Is this the sort of thing you meant @johav? :)

**Comment by Protohedgehog** [comment]
@katjamatic did you have a chance to add in this final paragraph yet? No worries if not!

**Comment by katjamatic** [comment]
oups, sorry,
I guess it would be better to move the pic a bit further below under
"....However,
the origins can probably go back even further to the very birth of
scholarly practices. Much of what we know about our world and universe has
foundations in fundamental openness, from evolution and the origin of
species, through to gravity and the origins of stars.", and then add it to
the following paragraph, which I cannot add directly at the moment since i
am on my mobile...



Am Do., 10. Jan. 2019 um 14:59 Uhr schrieb Jon Tennant <
notifications@github.com>:

**Comment by Protohedgehog** [comment]
Pic moved, thanks @katjamatic! And no rush at all :)

**Comment by katjamatic** [comment]
The technical foundations for Open Science were growing out of the
international e-science, e-research, or development of distributed learning
and knowledge production scene (REF). Historically this started with the
development of time sharing and distributed computing (REF). The free and
open software movement is also closely related to developments of Open
Science (REF). On the other hand the concept of "knowledge commons" -
collectively created and owned knowledge managed by a community - is traced
back by Hess and Ostrom (REF) both to the idea of the "Intangible commons
of the mind" (REF), which opposes increasing privatization of knowledge,
and to the idea of shared spaces for free speech and democratic collective
action (REF).

---- already now could come the text about Robert Merton -------- which
could be contrasted with Ziman (2000)'s critique of "post-academic"
science.  -----

Ziman (2000) constates a shift away from Merton's norms. Due to increased
economic interests, optimization of industrial research procedures,
overbureaucratization, we nowadays find an ethos that is more linked to the
following aspects:

Post-Academic Science: Ziman 2000
•P proprietarian ( IP, business opportunity)
•L local: related to local network of stakeholders
•A authoritarian: hierarchical control
•C commissioned (researcher is ’consultant’)
•E expert: role is problem-solver

Ziman states that “science is becoming a too large and expensive
enterprise. Governments are putting strict financial ceilings on their
patronage and are trying to get better value for their money”. In this
context, researchers are required to be more accountable, responsive to
societal need and concerned with the impact of their product in economic
and social terms." (REF)

-------Then continue with just briefly saying something like this:-----
However, the communal aspect of knowledge production in science and
research has been inspired by many other open cultures of collaboration and
sharing, such as open government data, and cultural heritage just to name a
few. Open Cultures have developed in the last decades often in parallel but
also overlapping. Open Science is thus embedded firmly in a manifold open
movement....

Am Fr., 11. Jan. 2019 um 15:50 Uhr schrieb Katja Mayer <katjamat@gmail.com>:

**Comment by katjamatic** [comment]
let me know what you think! will look up the refs when on a comp again.
best k (and sorry for all those delays and not working directly in the text)

Am Fr., 11. Jan. 2019 um 16:15 Uhr schrieb Katja Mayer <katjamat@gmail.com>:

**Comment by Protohedgehog** [comment]
Looks great, @katjamatic, thanks! Fills in a nice spot. No worries about the delays at all. If you can edit the text directly, that would be great, as it would ensure appropriate automatic credit for you. If not, I can wait for the refs and then edit this in after.

**Comment by Protohedgehog** [comment]
Hi @katjamatic, just bumping this again to keep on your radar in case it fell off :)

**Comment by katjamatic** [comment]
I think i entered the things some time ago directly in the text. Hope it
worked.  Best k

Am Di., 22. Jän. 2019, 17:53 hat Jon Tennant <notifications@github.com>
geschrieben:

**Comment by Protohedgehog** [comment]
I think [this section](https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/MAIN.md#history-of-open-science-and-open-cultures-) is looking okay, @katjamatic - thanks for your help with this, super appreciated! 

Can close this now :)
