### ISSUE TITLE
wonderful, but too long ? (discussion moved there OpenScienceMOOC/Main#25)

### ISSUE THREAD

**Issue by jcolomb** [OpenScienceMOOC/Module-1-Open-Principles#16]
I went through the amazing content. I think it will not fit into one hour.
On the other hand we probably need to discuss the structure of the MOOC, one hour might be already much too long. Maybe we need to split content (not only here, BTW) into beginner-intermediate-experts levels ?

I will get an issue in the main repo and get a discussion going on slack.

**Comment by Protohedgehog** [comment]
I've recorded it, it fits in at 58 minutes. Have also chopped it into 2 smaller chunks for on Eliademy.

**Comment by johav** [comment]
I think the beginner, intermediate-experts levels are a natural development for each as people go through the chapters of the MOOC. And they can decide how far they want to dive in and what to leave out or address later (in the day or in their career as needed)

**Comment by jcolomb** [comment]
I do not agree @johav, in addition, there are other things to consider as mentioned by @brucellino on slack, if one wants to be able to give credits, one needs to design the MOOC accordingly.
So nothithing I have experience with, but not something we can simply ignore.

**Comment by jcolomb** [comment]
But let's close the discussion here, and continue there: https://github.com/OpenScienceMOOC/Main/issues/25

It is indeed a question that goes beyond just this module.
