### ISSUE TITLE
clarify wording - add Open Research?

### ISSUE THREAD

**Issue by johav** [OpenScienceMOOC/Module-1-Open-Principles#8]
the science/research wikiperdians make a difference between Open Science and Open Research, the latter including math, humanities and social sciences: https://en.wikipedia.org/wiki/Open_research. 

Should we also clarify this or are focussing on Life Sciences with the MOOC?
Most applies to all disciplines - esp regarding Open Data would be useful to find cross-discipline standards

**Comment by Protohedgehog** [comment]
Some clarification might be needed here. We discuss this issue a lot in the main site, and can use some of the phrasing from there perhaps: https://opensciencemooc.eu/about/

**Comment by Remi-Gau** [comment]
I am having the same problem that is related to the different meaning that "science" can have.

I usually try to stick to the 4 fold definition of the word I found in "fashionable non-sense" by Sokal and Bricmont (see also paragraph 3 [here](https://scientiasalon.wordpress.com/2014/03/26/what-is-science-and-why-should-we-care-part-i/))

> The word science, as commonly used, has at least four distinct meanings: it denotes an **intellectual endeavor aimed at a rational understanding of the natural and social world**; it denotes **a corpus of currently accepted substantive knowledge**; it denotes the **community of scientists**, with its mores and its social and economic structure; and, finally, it denotes **applied science and technology.** 

What I like with this manyfold definition in the context of open science is that it also adresses the fact that for example we want transparent research and accessible data (roughly falls under definition 1 and 2), but also an inclusive community for all (no matter your class, race, gender...) and the ability to share our results/papers "free of charges" (definition 3).

**Comment by Protohedgehog** [comment]
What I've tried to do throughout here is use the term Open Science, but otherwise refer to 'research' where needed. What do you think? Feel free to make edits if needed, or let me know where changes need to be made! https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/MAIN.md @johav

**Comment by johav** [comment]
What about adding a Glossary to the MOOC?

**Comment by Protohedgehog** [comment]
@johav We have one already that could be linked to more clearly! https://openresearchglossary.herokuapp.com/

**Comment by johav** [comment]
hm... yes, I see. Still having a glossary inside the MOOC with OS-MOOC specific terminology being clarified according to "our" (OS-MOOC community) view therefore streamlining Open Science, Open Research etc into the same concept. 
And of course also linking to the research coalition and other OS glossaries for further info.

I don't think we should add all obvious terms like Open Acces and such trivials, or maybe in short with referring to a wikipedia article and recent research literature for further info also on these... it's a whole task on iot's own but i think it could add tremendous USP value to the whole project, given that other OS tutorials and courses are popping up each day

**Comment by Protohedgehog** [comment]
OK, nice idea. Maybe we can just create this in the 'Main' repo and start collecting terms, and then link it into each module where needed?

**Comment by johav** [comment]
quickly made this tbc: https://github.com/OpenScienceMOOC/Main/blob/master/Glossary.md

**Comment by Protohedgehog** [comment]
Ooh, nice work @johav, thank you!

**Comment by tosteiner** [comment]
I guess since this module is about the underlying principles, we could also make use of some of the broader definitions developed over at https://github.com/Open-Scholarship-Strategy/site - what do you think? 

I'm still a bit hesitant about the Science vs. Research debate, because I feel it omits an important segment of academic life: that of teaching, which many researchers are also involved in ("teaching" not as in "edu science", but as in "scholarly practice of sharing knowledge, customs, etc as a researcher in lectures, seminars, etc. ") ... and of course, one might argue that OER are an important tenet for that, but actually providing researchers with the means to communicate what they're doing in a way that students are inspired is not done by OER alone ... :) @Protohedgehog I think this is something that we and quite a few people discussed over at the [OScholarshipStrategy](https://github.com/Open-Scholarship-Strategy/site) project - do you think there's room for that here at the OSMOOC as well?

**Comment by Protohedgehog** [comment]
This is such a good point @tosteiner, and I think you're right that perhaps we've glossed over this a bit too much. 

So, I have an idea. What about for the intro video for this module, we do a series of short videos with folks about 'What does OS mean for you', and have you as part of this discussing this point you raise here? That might be super interesting! 

But yes, perhaps we also can/should draw more on the Strategy for parts of this too.

**Comment by johav** [comment]
I agree!
As each community seems to define OS more or less differently - is it time already and this a good forum to crystallise out a general definition or clarification of distinguishing between OS/OR/OScholars that works for all disciplines? Might also help in future reference and academic publications on the matter for mutual understanding what which stakeholder means by referring to OS.
Is that worth a review paper? - Could be tied to / base on /refer to the intro video

**Comment by tosteiner** [comment]
Couldn't agree more, @johav - I guess it's something that we as OSMOOC community need to define how we want to position ourselves... regarding the general conceptual distinctions and overlaps, there's quite a collection of existing literature, some of which is referenced over at the Strategy site, but I guess to tie things down, a review paper might prove quite helpful for future communities and institutions, yes - how about something done collaboratively? ;) Would be definitely interested in contributing :) 

And @Protohedgehog re: intro video - great idea, yes! what also might help is a combination of video and text statements, so to include people who maybe don't feel comfortable appearing on video

**Comment by Protohedgehog** [comment]
So actually, someone got in touch with me recently about this exact problem. This new platform, Qeios, is designed to help create precise definitions around scholarly terms: https://www.qeios.com/ - I imagine we could use this to do one for Open Research/Science/Scholarship. There is a systematic review of Open Science, but it's paywalled by Elsevier.

As for the MOOC stance on this, we have statements here: https://opensciencemooc.eu/about/ but these can be adapted if needed.

For the video, I have created a separate issue for this now #12. Love the idea of including text statements too, possibly screenshots of tweets following a little campaign for this.

**Comment by Protohedgehog** [comment]
Gonna close this for now as it seems to be okay
