### ISSUE TITLE
mention ORCID-CrossRef integration before manual adding

### ISSUE THREAD

**Issue by egonw** [OpenScienceMOOC/Module-1-Open-Principles#9]
Because most people get most done with that integration, and it would be annoying to have added a few manually, and then a bit later read that you could have done it easier. Moreover, the integration auto-updates and manual adding/editing should really only be used for things which cannot be done automatically.

Solution: mention the integrations *before* the manual adding.

**Comment by Protohedgehog** [comment]
I think that is the case! See how it goes from Direct, to BibTeX, to Manual here: https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/Task_2.md#populating-your-orcid-profile

Do you think it needs to be made more clear? @egonw

**Comment by egonw** [comment]
I see that now. I will see if I can make a suggestion to make it more to my liking :)

**Comment by Protohedgehog** [comment]
OK, great! Bear with one minute and let me push new changes to the doc @egonw :)

**Comment by Protohedgehog** [comment]
Hey @egonw, any thoughts on how to improve this for now? :)

**Comment by alainna** [comment]
I've been making some changes to a local version of the ORCID section, to include info about the Crossref and DataCite auto-updates, as well as add details about other systems that also include connections (e.g. INSPIRE, which has an auto-update and enables arXiv works to be added to records 🛩 )

hopefully will have this all ready for a pull this week 😺 

let me know if any other ORCIDy things we could add in it 😉

**Comment by egonw** [comment]
Hi all, I'm sorry I did not have time yet... end of year chaos... too many deliverables and deadlines :( I'll check it as soon as possible and hope that that will be soon...

**Comment by Protohedgehog** [comment]
Thank you so much, @alainna, that sounds amazing! Really looking forward to seeing this. @egonw no worries either, no rush on this. Perhaps better to wait and see what @alainna has altered and then see how to build on top of that contribution if needed? :)

**Comment by Protohedgehog** [comment]
Hey @egonw any progress on this now we're in the new year? Would be great to get finalised before production :)

**Comment by egonw** [comment]
Ping received... it's on my schedule.

**Comment by Protohedgehog** [comment]
Perfect, dank je!

**Comment by egonw** [comment]
Sorry. Things are not going as planned (planning is impossible in my function, I've experimentally discovered). I'm closing this one.

**Comment by Protohedgehog** [comment]
OK, no worries @egonw, I think we have this pretty much covered anyway :)
